CREATE TABLE IF NOT EXISTS `people_tmp` (
  `id` INT(11) UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '主键 ID',
  `name` VARCHAR(30) NOT NULL DEFAULT '' COMMENT '名字',
  `age` INT(5) UNSIGNED NOT NULL DEFAULT '0' COMMENT '年龄',
  `gender` VARCHAR(10) NOT NULL DEFAULT '' COMMENT '性别',
  `income` INT(11) UNSIGNED NOT NULL DEFAULT '0' COMMENT '工资',
  `created_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP COMMENT '创建时间',
  `updated_at` TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP COMMENT '更新时间',
PRIMARY KEY (`id`),
KEY `ix_age` (`age`),
KEY `ix_created_at` (`created_at`),
KEY `ix_updated_at` (`updated_at`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8 COMMENT='测试用人员信息表';
